apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../../global/argocd

# This will automate the manually created ArgoCD helm chart.
# Any future changes to the ArgoCD helm chart will be reflected in this ArgoCD application.
patches:
- target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
    name: argo-cd
  patch: |-
    - op: replace
      path: /spec/project
      value: dev-cluster-01-charts
