# Directory pattern
development:
  - changed-files:
      - any-glob-to-any-file: 'environments/development/**'

production:
  - changed-files:
      - any-glob-to-any-file: "environments/production/**"
