apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  projects: ""
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    targetRevision: 1.21.1
    chart: external-dns
    helm:
      releaseName: external-dns
      # Generic values that remain static across all environments
      valuesObject:
        sources:
          - service
          - ingress
        policy: upsert-only
        replicaCount: 1
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        serviceAccount:
          create: true
  destination:
    name: in-cluster
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
