apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev-cluster-01-charts
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: "*"
    kind: "*"
  description: "All charts deployed on dev-cluster-01"
  sourceRepos:
  - "https://charts.jetstack.io"
  - "https://charts.external-secrets.io"
  destinations:
  - namespace: "*"
    server: https://kubernetes.default.svc
  - namespace: '*'
    name: dev-cluster-01
