# Example CRD config deployed outside of the main helm chart
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: dev-cluster-01-secret-store
  namespace: external-secrets-operator
spec:
  # Google cloud provider for example use
  provider:
    gcpsm:
      projectID: dev-cluster-01
