apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: development-root-app
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: "*"
    kind: "*"
  description: "Root application project for development environment"
  sourceRepos:
  - "*"
  destinations:
  - namespace: "*"
    server: https://kubernetes.default.svc
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: development-root-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: development-root-app
  source:
    repoURL: "https://github.com/cloudoutloud/platform-helm-charts"
    path: environments/development/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
