# A github action to check kustomize can build manifests successfully
name: 'Kustomize Build'

# Can trigger manually or automatically when a pull request is made to the main branch
on:
  workflow_dispatch:
  pull_request:
    branches:
    - main

jobs:
  kustomize:
    name: 'Kustomize build'
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Kustomize build development environment'
      uses: karancode/kustomize-github-action@v1.3.2
      with:
        kustomize_version: '5.4.3'
        token: ${{ secrets.GITHUB_TOKEN }}
        kustomize_build_dir: 'environments/development'

    - name: 'Kustomize build production environment'
      uses: karancode/kustomize-github-action@v1.3.2
      with:
        kustomize_version: '5.4.3'
        token: ${{ secrets.GITHUB_TOKEN }}
        kustomize_build_dir: 'environments/production'
