name: 'PR Labeler'

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  label:
    name: 'label'
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: 'labeler'
        uses: actions/labeler@v5
        with:
          configuration-path: .github/configs/labeler.yaml
